### ISSUE TITLE
MSB4066 does not recognize the attribute "d2p1:Project" in the element <Import>

### ISSUE THREAD

**Issue by FreeVB** [rapiddev/MaterialWPF#1]
MSB4066 does not recognize the attribute "d2p1:Project" in the element <Import>

When compiling, MSB4066 cannot recognize the feature "d2p1:Project" in the element <Import>. What is the reason?

**Comment by Pomianowski** [comment]
Could you please discuss in more detail in which situation the error occurs?

1. Are you using Visual Studio 2019 updated to the latest version?
2. Do you have .NET 5 Runtime installed?
3. Do you have .NET desktop development installed?
(C# and Visual Basic)
(.NET desktop development tools)

**Comment by FreeVB** [comment]
All of these are correct, and I have not modified any code.

**Comment by FreeVB** [comment]
Congratulations! By comparing other normally compiled projects, I found the cause of this error: Put MaterialWPF.csproj's <Project Sdk="Microsoft.NET.Sdk.WindowsDesktop" xmlns="http://schemas.microsoft.com/developer/msbuild/ 2003">Modify it to <Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">.

**Comment by FreeVB** [comment]
Congratulations! By comparing other normally compiled projects, I found the cause of this error: Put MaterialWPF.csproj's <Project Sdk="Microsoft.NET.Sdk.WindowsDesktop" xmlns="http://schemas.microsoft.com/developer/msbuild/ 2003">Modify it to <Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">.
